agent_id = "01b6ebbf-d419-4ceb-a293-1b3d01c958ed"
server = "https://cloudpub.ru/"
heartbeat_timeout = 40
minimize_to_tray_on_close = true
minimize_to_tray_on_start = false

[transport]
type = "websocket"

[transport.tcp]
connect_timeout_secs = 30

[transport.tls]

[transport.websocket]
tls = true
